export const SLICE_NAME = 'countries';
export const UPDATE_SEARCH_VALUE = `${SLICE_NAME}/UPDATE_SEARCH_VALUE`;
export const FETCH_COUNTRIES_FAILURE = `${SLICE_NAME}/FETCH_COUNTRIES_FAILURE`;
export const FETCH_COUNTRIES_SUCCESS = `${SLICE_NAME}/FETCH_COUNTRIES_SUCCESS`;
export const SHOW_LOADER = `${SLICE_NAME}/SHOW_LOADER`;
export const HIDE_LOADER = `${SLICE_NAME}/HIDE_LOADER`;
