const COUNTRIES_STATE = 'COUNTRIES'

export const UPDATE_SEARCH_VALUE = `${COUNTRIES_STATE}/UPDATE_SEARCH_VALUE`

export const FETCH_COUNTRIES_FAILURE = `${COUNTRIES_STATE}/FETCH_COUNTRIES_FAILURE`
export const FETCH_COUNTRIES_SUCCESS = `${COUNTRIES_STATE}/FETCH_COUNTRIES_SUCCESS`;
export const SHOW_ERROR = `${COUNTRIES_STATE}/SHOW_ERROR`;
export const SHOW_LOADER = `${COUNTRIES_STATE}/SHOW_LOADER`;
export const HIDE_LOADER = `${COUNTRIES_STATE}/HIDE_LOADER`;

