export const SLICE_NAME = 'country';
export const FETCH_COUNTRY_FAILURE = `${SLICE_NAME}/FETCH_COUNTRY_FAILURE`;
export const FETCH_COUNTRY_SUCCESS = `${SLICE_NAME}/FETCH_COUNTRY_SUCCESS`;
export const SHOW_LOADER = `${SLICE_NAME}/SHOW_LOADER`;
export const HIDE_LOADER = `${SLICE_NAME}/HIDE_LOADER`;
export const GET_COUNTRY_ID = `${SLICE_NAME}/GET_COUNTRY_ID`;
export const SET_RATE_FAILURE = `${SLICE_NAME}/SET_RATE_FAILURE`;
export const UPDATE_PLACE = `${SLICE_NAME}/UPDATE_PLACE`;
